version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - socket
    env_file:
      - ./frontend/.env
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  socket:
    build: ./backend/realtime
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_secure_password
      - MYSQL_DATABASE=match_study
      - MYSQL_USER=match_study_user
      - MYSQL_PASSWORD=secure_password123
    ports:
      - "3307:3306"
    restart: always
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql_data:
