version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - socket
    environment:
      - VITE_APP_API_URL=/api
      - VITE_APP_SOCKET_URL=''
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=match_study_user
      - DB_PASSWORD=Klmn5512300.
      - DB_NAME=match_study
    depends_on:
      - db
    restart: always

  socket:
    build: ./backend/realtime
    ports:
      - "3000:3000"
    volumes:
      - socket_logs:/app/logs
    environment:
      - DB_HOST=db
      - DB_USER=match_study_user
      - DB_PASSWORD=Klmn5512300.
      - DB_NAME=match_study
      - CORS_ORIGINS=http://localhost,http://frontend,*
      - NODE_ENV=production
      - DEBUG=socket.io*
    depends_on:
      - db
    restart: always
    networks:
      - default

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password123
      - MYSQL_DATABASE=match_study
      - MYSQL_USER=match_study_user
      - MYSQL_PASSWORD=Klmn5512300.
    ports:
      - "3307:3306"
    restart: always
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql_data:
  socket_logs:

networks:
  default:
